# nethogs
# Autogenerated from man page /usr/share/man/man8/nethogs.8.gz
complete -c nethogs -s V -d 'prints version'
complete -c nethogs -s h -d 'prints available commands usage'
complete -c nethogs -s x -d 'bughunt mode - implies tracemode'
complete -c nethogs -s d -d 'delay for update refresh rate in seconds.  default is 1'
complete -c nethogs -s v -d 'view mode (0 = KB/s, 1 = total KB, 2 = total B, 3 = total MB, 4 = MB/s, 5 = G…'
complete -c nethogs -s c -d 'number of updates.  default is 0 (unlimited)'
complete -c nethogs -s t -d tracemode
complete -c nethogs -s p -d 'sniff in promiscuous mode (not recommended)'
complete -c nethogs -s s -d 'sort output by sent column'
complete -c nethogs -s l -d 'display command line'
complete -c nethogs -s a -d 'monitor all devices, even loopback/stopped ones'
complete -c nethogs -s C -d 'capture TCP and UDP'
complete -c nethogs -s b -d 'Display the program basename'
complete -c nethogs -s g -d 'garbage collection period in number of refresh.  default is 50'
complete -c nethogs -s P -d 'Show only processes with the specified pid(s)'
complete -c nethogs -s f -d 'EXPERIMENTAL: specify string pcap filter (like tcpdump)'

