# oct-sign-detached
# Autogenerated from man page /usr/share/man/man1/oct-sign-detached.1.gz
complete -c oct-sign-detached -s o -l output -d 'Output file (stdout if unset)'
complete -c oct-sign-detached -s h -l help -d 'Print help'

