# oct-pin
# Autogenerated from man page /usr/share/man/man1/oct-pin.1.gz
complete -c oct-pin -s c -l card -d 'Identifier of the card to use'
complete -c oct-pin -s h -l help -d 'Print help (see a summary with \\-h) SUBCOMMANDS'

