# oct-admin-signing-pin-validity
# Autogenerated from man page /usr/share/man/man1/oct-admin-signing-pin-validity.1.gz
complete -c oct-admin-signing-pin-validity -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

