# oct-admin-touch
# Autogenerated from man page /usr/share/man/man1/oct-admin-touch.1.gz
complete -c oct-admin-touch -s k -l key -d 'Key slot to set the touch policy for . br  '
complete -c oct-admin-touch -s p -l policy -d 'Touch policy to set on this key slot  Off: No touch confirmation required'
complete -c oct-admin-touch -s h -l help -d 'Print help (see a summary with \\-h)'

