# oct-decrypt
# Autogenerated from man page /usr/share/man/man1/oct-decrypt.1.gz
complete -c oct-decrypt -s c -l card -d 'Identifier of the card to use'
complete -c oct-decrypt -s p -l user-pin -d 'Optionally, get User PIN from a file'
complete -c oct-decrypt -s o -l output -d 'Output file (stdout if unset)'
complete -c oct-decrypt -s h -l help -d 'Print help'

