# oct-pin-set-user
# Autogenerated from man page /usr/share/man/man1/oct-pin-set-user.1.gz
complete -c oct-pin-set-user -s p -l user-pin-old -d 'Optionally, get old User PIN from a file'
complete -c oct-pin-set-user -s q -l user-pin-new -d 'Optionally, get new User PIN from a file'
complete -c oct-pin-set-user -s h -l help -d 'Print help (see a summary with \\-h)'

