# oct-attestation-statement
# Autogenerated from man page /usr/share/man/man1/oct-attestation-statement.1.gz
complete -c oct-attestation-statement -s c -l card -d 'Identifier of the card to reset'
complete -c oct-attestation-statement -s k -l key -d 'Key slot to use . br  . br [possible values: SIG, DEC, AUT]'
complete -c oct-attestation-statement -s h -l help -d 'Print help (see a summary with \\-h)'

