# oct-system-activate-file
# Autogenerated from man page /usr/share/man/man1/oct-system-activate-file.1.gz
complete -c oct-system-activate-file -s h -l help -d 'Print help (see a summary with \\-h)'

