# oct-pin-reset-user
# Autogenerated from man page /usr/share/man/man1/oct-pin-reset-user.1.gz
complete -c oct-pin-reset-user -s P -l admin-pin -d 'Optionally, get Admin PIN from a file'
complete -c oct-pin-reset-user -s p -l user-pin-new -d 'Optionally, get new User PIN from a file'
complete -c oct-pin-reset-user -s h -l help -d 'Print help (see a summary with \\-h)'

