# oct-attestation-generate
# Autogenerated from man page /usr/share/man/man1/oct-attestation-generate.1.gz
complete -c oct-attestation-generate -s c -l card -d 'Identifier of the card to use'
complete -c oct-attestation-generate -s k -l key -d 'Key slot to use . br  . br [possible values: SIG, DEC, AUT]'
complete -c oct-attestation-generate -s p -l user-pin -d 'Optionally, get User PIN from a file'
complete -c oct-attestation-generate -s h -l help -d 'Print help (see a summary with \\-h)'

