# oct-system-kdf-setup
# Autogenerated from man page /usr/share/man/man1/oct-system-kdf-setup.1.gz
complete -c oct-system-kdf-setup -s c -l card -d 'Identifier of the card to use'
complete -c oct-system-kdf-setup -s h -l help -d 'Print help'

