# oct-status
# Autogenerated from man page /usr/share/man/man1/oct-status.1.gz
complete -c oct-status -s c -l card -d 'Identifier of the card to use'
complete -c oct-status -s v -l verbose -d 'Use verbose output'
complete -c oct-status -s K -l public-key-material -d 'Print public key material for each key slot'
complete -c oct-status -s h -l help -d 'Print help'

