# oct-admin-import
# Autogenerated from man page /usr/share/man/man1/oct-admin-import.1.gz
complete -c oct-admin-import -s s -l sig-fp -d 'Optionally, select the subkey to import in the SIG slot'
complete -c oct-admin-import -s d -l dec-fp -d 'Optionally, select the subkey to import in the DEC slot'
complete -c oct-admin-import -s a -l aut-fp -d 'Optionally, select the subkey to import in the AUT slot'
complete -c oct-admin-import -l key-passphrase -d 'Optionally, provide a passphrase for encrypted secret key material in a file'
complete -c oct-admin-import -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

