# oct-system-set-identity
# Autogenerated from man page /usr/share/man/man1/oct-system-set-identity.1.gz
complete -c oct-system-set-identity -s c -l card -d 'Identifier of the card to use'
complete -c oct-system-set-identity -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

