# oct-system-factory-reset
# Autogenerated from man page /usr/share/man/man1/oct-system-factory-reset.1.gz
complete -c oct-system-factory-reset -s c -l card -d 'Identifier of the card to use'
complete -c oct-system-factory-reset -s h -l help -d 'Print help'

