# oct-pin-set-reset
# Autogenerated from man page /usr/share/man/man1/oct-pin-set-reset.1.gz
complete -c oct-pin-set-reset -s P -l admin-pin -d 'Optionally, get Admin PIN from a file'
complete -c oct-pin-set-reset -s r -l reset-code -d 'Optionally, get the Resetting Code from a file'
complete -c oct-pin-set-reset -s h -l help -d 'Print help (see a summary with \\-h)'

