# oct-attestation-cert
# Autogenerated from man page /usr/share/man/man1/oct-attestation-cert.1.gz
complete -c oct-attestation-cert -s c -l card -d 'Identifier of the card to use'
complete -c oct-attestation-cert -s h -l help -d 'Print help (see a summary with \\-h)'

