# oct-admin
# Autogenerated from man page /usr/share/man/man1/oct-admin.1.gz
complete -c oct-admin -s c -l card -d 'Identifier of the card to use'
complete -c oct-admin -s P -l admin-pin -d 'Optionally, get Admin PIN from a file'
complete -c oct-admin -s h -l help -d 'Print help SUBCOMMANDS'

