# oct-ssh
# Autogenerated from man page /usr/share/man/man1/oct-ssh.1.gz
complete -c oct-ssh -s c -l card -d 'Identifier of the card to use'
complete -c oct-ssh -l key-only -d 'Only print the ssh public key'
complete -c oct-ssh -s h -l help -d 'Print help'

