# oct-pin-set-admin
# Autogenerated from man page /usr/share/man/man1/oct-pin-set-admin.1.gz
complete -c oct-pin-set-admin -s P -l admin-pin-old -d 'Optionally, get old Admin PIN from a file'
complete -c oct-pin-set-admin -s Q -l admin-pin-new -d 'Optionally, get new Admin PIN from a file'
complete -c oct-pin-set-admin -s h -l help -d 'Print help (see a summary with \\-h)'

