# oct-sign-inline
# Autogenerated from man page /usr/share/man/man1/oct-sign-inline.1.gz
complete -c oct-sign-inline -s o -l output -d 'Output file (stdout if unset)'
complete -c oct-sign-inline -s h -l help -d 'Print help'

