# oct-pubkey
# Autogenerated from man page /usr/share/man/man1/oct-pubkey.1.gz
complete -c oct-pubkey -s c -l card -d 'Identifier of the card to use'
complete -c oct-pubkey -s p -l user-pin -d 'Optionally, get User PIN from a file'
complete -c oct-pubkey -s u -l userid -d 'User ID to add to the exported certificate representation'
complete -c oct-pubkey -s h -l help -d 'Print help'

