# oct-admin-generate
# Autogenerated from man page /usr/share/man/man1/oct-admin-generate.1.gz
complete -c oct-admin-generate -s o -l output -d 'Output file'
complete -c oct-admin-generate -l no-dec -d 'Do not create a key in the DEC slot'
complete -c oct-admin-generate -l no-aut -d 'Do not create a key in the AUT slot'
complete -c oct-admin-generate -s u -l userid -d 'User ID to add to the exported certificate representation'
complete -c oct-admin-generate -s p -l user-pin -d 'Optionally, get User PIN from a file'
complete -c oct-admin-generate -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

