# oct-sign
# Autogenerated from man page /usr/share/man/man1/oct-sign.1.gz
complete -c oct-sign -s c -l card -d 'Identifier of the card to use'
complete -c oct-sign -s p -l user-pin -d 'Optionally, get User PIN from a file'
complete -c oct-sign -s h -l help -d 'Print help SUBCOMMANDS'

