# oct-pin-reset-user-rc
# Autogenerated from man page /usr/share/man/man1/oct-pin-reset-user-rc.1.gz
complete -c oct-pin-reset-user-rc -s r -l reset-code -d 'Optionally, get the Resetting Code from a file'
complete -c oct-pin-reset-user-rc -s p -l user-pin-new -d 'Optionally, get new User PIN from a file'
complete -c oct-pin-reset-user-rc -s h -l help -d 'Print help (see a summary with \\-h)'

