# oct
# Autogenerated from man page /usr/share/man/man1/oct.1.gz
complete -c oct -l output-format -d 'Produce output in the chosen format . br  '
complete -c oct -l output-version -d 'Pick output version to use, for non-textual formats'
complete -c oct -s h -l help -d 'Print help'
complete -c oct -s V -l version -d 'Print version SUBCOMMANDS'

