# sq-autocrypt-encode-sender
# Autogenerated from man page /usr/share/man/man1/sq-autocrypt-encode-sender.1.gz
complete -c sq-autocrypt-encode-sender -l email -d 'Set the address [default: primary userid]'
complete -c sq-autocrypt-encode-sender -s o -l output -d 'Write to FILE or stdout if omitted'
complete -c sq-autocrypt-encode-sender -l prefer-encrypt -d 'Set the prefer-encrypt attribute'

