# sq-autocrypt-import
# Autogenerated from man page /usr/share/man/man1/sq-autocrypt-import.1.gz
complete -c sq-autocrypt-import -l recipient-file -d 'Decrypt the message using the key in KEY_FILE'
complete -c sq-autocrypt-import -l session-key -d 'Decrypt an encrypted message using SESSION-KEY'

