# sq-cert-lint
# Autogenerated from man page /usr/share/man/man1/sq-cert-lint.1.gz
complete -c sq-cert-lint -s B -l binary -d 'Emit binary data'
complete -c sq-cert-lint -s F -l fix -d 'Attempts to fix certificates, when possible'
complete -c sq-cert-lint -l cert -d 'Lint the specified certificate'
complete -c sq-cert-lint -l cert-file -d 'Lint the certificates in the specified file'
complete -c sq-cert-lint -s e -l export-secret-keys -d 'When fixing a certificate, the fixed certificate is exported without any secr…'
complete -c sq-cert-lint -s k -l list-keys -d 'If set, outputs a list of fingerprints, one per line, of certificates that ha…'
complete -c sq-cert-lint -s o -l output -d 'Write to the specified FILE'
complete -c sq-cert-lint -s q -l quiet -d 'Quiet; does not output any diagnostics Global options See sq(1) for a descrip…'

