# sq-cert-export
# Autogenerated from man page /usr/share/man/man1/sq-cert-export.1.gz
complete -c sq-cert-export -s B -l binary -d 'Emit binary data'
complete -c sq-cert-export -l all -d 'Export all certificates'
complete -c sq-cert-export -l cert -d 'Return certificates that have the specified fingerprint or key ID'
complete -c sq-cert-export -l domain -d 'Return certificates that have a User ID with an email address from the specif…'
complete -c sq-cert-export -l email -d 'Return certificates that have a User ID with the specified email address, cas…'
complete -c sq-cert-export -l grep -d 'Return certificates that have a User ID that contains the string, case insens…'
complete -c sq-cert-export -l key -d 'Return certificates where the primary key or a subkey has the specified finge…'
complete -c sq-cert-export -l userid -d 'Return certificates that have a User ID that matches exactly, including case'

