# sq-decrypt
# Autogenerated from man page /usr/share/man/man1/sq-decrypt.1.gz
complete -c sq-decrypt -l dump-session-key -d 'Print the session key to stderr'
complete -c sq-decrypt -s n -l signatures -d 'Set the threshold of valid signatures to N'
complete -c sq-decrypt -s o -l output -d 'Write to FILE or stdout if omitted'
complete -c sq-decrypt -l recipient-file -d 'Decrypt the message using the key in KEY_FILE'
complete -c sq-decrypt -l session-key -d 'Decrypt an encrypted message using SESSION-KEY'
complete -c sq-decrypt -l signer-file -d 'Verify signatures using the certificates in CERT_FILE'

