# sq-encrypt
# Autogenerated from man page /usr/share/man/man1/sq-encrypt.1.gz
complete -c sq-encrypt -s B -l binary -d 'Emit binary data'
complete -c sq-encrypt -l compression -d 'Select compression scheme to use'
complete -c sq-encrypt -l encrypt-for -d 'Select what kind of keys are considered for encryption'
complete -c sq-encrypt -s o -l output -d 'Write to FILE or stdout if omitted'
complete -c sq-encrypt -l recipient-cert -d 'Encrypt to the named certificates'
complete -c sq-encrypt -l recipient-email -d 'Encrypt to all certificates that can be authenticated for the specified email…'
complete -c sq-encrypt -l recipient-file -d 'Encrypt to all certificates in CERT_RING_FILE'
complete -c sq-encrypt -l recipient-userid -d 'Encrypt to all certificates that can be authenticated for the specified User …'
complete -c sq-encrypt -s s -l symmetric -d 'Prompt to add a password to encrypt with'
complete -c sq-encrypt -l set-metadata-filename -d 'Set the filename of the encrypted file as metadata'
complete -c sq-encrypt -l set-metadata-time -d 'Set time for encrypted file as metadata'
complete -c sq-encrypt -l signer-file -d 'Sign the message using the key in KEY_FILE'
complete -c sq-encrypt -l signer-key -d 'Sign the message using the specified key on the key store'
complete -c sq-encrypt -l use-expired-subkey -d 'If a certificate has only expired encryption-capable subkeys, fall back to us…'

