# sq-inspect
# Autogenerated from man page /usr/share/man/man1/sq-inspect.1.gz
complete -c sq-inspect -l cert -d 'Read the specified certificate from the certificate store'
complete -c sq-inspect -l certifications -d 'Print third-party certifications'

