# sq-key-userid-add
# Autogenerated from man page /usr/share/man/man1/sq-key-userid-add.1.gz
complete -c sq-key-userid-add -s B -l binary -d 'Emit binary data'
complete -c sq-key-userid-add -l allow-non-canonical-userids -d 'Don\'t reject user IDs that are not in canonical form'
complete -c sq-key-userid-add -l cert -d 'Add the user ID to the specified certificate'
complete -c sq-key-userid-add -l cert-file -d 'Add the user ID to the specified certificate'
complete -c sq-key-userid-add -s o -l output -d 'Write to the specified FILE'
complete -c sq-key-userid-add -l userid -d 'User ID to add Global options See sq(1) for a description of the global optio…'

