# sq-key-subkey-expire
# Autogenerated from man page /usr/share/man/man1/sq-key-subkey-expire.1.gz
complete -c sq-key-subkey-expire -s B -l binary -d 'Emit binary data'
complete -c sq-key-subkey-expire -l cert -d 'Change the expiration time of keys on the specified certificate'
complete -c sq-key-subkey-expire -l cert-file -d 'Change the expiration time of keys on the specified certificate'
complete -c sq-key-subkey-expire -l key -d 'Change the expiration of this subkey'
complete -c sq-key-subkey-expire -s o -l output -d 'Write to the specified FILE'

