# sq-key-userid-strip
# Autogenerated from man page /usr/share/man/man1/sq-key-userid-strip.1.gz
complete -c sq-key-userid-strip -s B -l binary -d 'Emit binary data'
complete -c sq-key-userid-strip -s o -l output -d 'Write to FILE or stdout if omitted'
complete -c sq-key-userid-strip -s u -l userid -d 'The User IDs to strip.   Values must exactly match a User ID'

