# sq-key-subkey-add
# Autogenerated from man page /usr/share/man/man1/sq-key-subkey-add.1.gz
complete -c sq-key-subkey-add -s B -l binary -d 'Emit binary data'
complete -c sq-key-subkey-add -s c -l cipher-suite -d 'Select the cryptographic algorithms for the subkey'
complete -c sq-key-subkey-add -l can-authenticate -d 'Add an authentication-capable subkey'
complete -c sq-key-subkey-add -l can-encrypt -d 'Add an encryption-capable subkey'
complete -c sq-key-subkey-add -l can-sign -d 'Add a signing-capable subkey'
complete -c sq-key-subkey-add -l cert -d 'Add a subkey to the specified certificate'
complete -c sq-key-subkey-add -l cert-file -d 'Add a subkey to the specified certificate'
complete -c sq-key-subkey-add -l expiration -d 'Sets the key\'s expiration time'
complete -c sq-key-subkey-add -s o -l output -d 'Write to the specified FILE'
complete -c sq-key-subkey-add -l with-password -d 'Protect the subkey\'s secret key material with a password Global options See s…'

