# sq-key-expire
# Autogenerated from man page /usr/share/man/man1/sq-key-expire.1.gz
complete -c sq-key-expire -s B -l binary -d 'Emit binary data'
complete -c sq-key-expire -l cert -d 'Change the certificate\'s expiration time'
complete -c sq-key-expire -l cert-file -d 'Change the certificate\'s expiration time'
complete -c sq-key-expire -s o -l output -d 'Write to FILE or stdout if omitted'

