# sq-key-export
# Autogenerated from man page /usr/share/man/man1/sq-key-export.1.gz
complete -c sq-key-export -l cert -d 'Export the specified certificate with its secret key material'
complete -c sq-key-export -l key -d 'Export the specified key'

