# sq-key-attest-certifications
# Autogenerated from man page /usr/share/man/man1/sq-key-attest-certifications.1.gz
complete -c sq-key-attest-certifications -s B -l binary -d 'Emit binary data'
complete -c sq-key-attest-certifications -l all -d 'Attest to all certifications'
complete -c sq-key-attest-certifications -l cert -d 'Change attestations on the specified certificate'
complete -c sq-key-attest-certifications -l cert-file -d 'Change attestations on the specified certificate'
complete -c sq-key-attest-certifications -l none -d 'Remove all prior attestations'
complete -c sq-key-attest-certifications -s o -l output -d 'Write to the specified FILE'

