# sq-key-adopt
# Autogenerated from man page /usr/share/man/man1/sq-key-adopt.1.gz
complete -c sq-key-adopt -s B -l binary -d 'Emit binary data'
complete -c sq-key-adopt -l allow-broken-crypto -d 'Allow adopting keys from certificates using broken cryptography'
complete -c sq-key-adopt -l cert -d 'Add keys to the specified certificate'
complete -c sq-key-adopt -l cert-file -d 'Add keys to the specified certificate'
complete -c sq-key-adopt -l expiration -d 'Make adopted subkeys expire at the given time'
complete -c sq-key-adopt -s k -l key -d 'Add the key or subkey KEY to the certificate'
complete -c sq-key-adopt -s o -l output -d 'Write to the specified FILE'

