# sq-key-generate
# Autogenerated from man page /usr/share/man/man1/sq-key-generate.1.gz
complete -c sq-key-generate -l allow-non-canonical-userids -d 'Don\'t reject user IDs that are not in canonical form'
complete -c sq-key-generate -s c -l cipher-suite -d 'Select the cryptographic algorithms for the key'
complete -c sq-key-generate -l can-authenticate -d 'Add an authentication-capable subkey (default)'
complete -c sq-key-generate -l can-encrypt -d 'Add an encryption-capable subkey'
complete -c sq-key-generate -l can-sign -d 'Add a signing-capable subkey (default)'
complete -c sq-key-generate -l cannot-authenticate -d 'Don\'t add an authentication-capable subkey'
complete -c sq-key-generate -l cannot-encrypt -d 'Don\'t add an encryption-capable subkey'
complete -c sq-key-generate -l cannot-sign -d 'Don\'t add a signing-capable subkey'
complete -c sq-key-generate -l expiration -d 'Sets the certificate\'s expiration time'
complete -c sq-key-generate -l no-userids -d 'Create a key without any user IDs'
complete -c sq-key-generate -s o -l output -d 'Write the key to the specified file'
complete -c sq-key-generate -l rev-cert -d 'Write the emergency revocation certificate to FILE'
complete -c sq-key-generate -s u -l userid -d 'Add a user ID to the key'
complete -c sq-key-generate -l with-password -d 'Protect the secret key material with a password Global options See sq(1) for …'

