# sq-key-subkey-revoke
# Autogenerated from man page /usr/share/man/man1/sq-key-subkey-revoke.1.gz
complete -c sq-key-subkey-revoke -s B -l binary -d 'Emit binary data'
complete -c sq-key-subkey-revoke -l cert -d 'Revoke the subkey on the specified certificate'
complete -c sq-key-subkey-revoke -l cert-file -d 'Revoke the subkey on the specified certificate'
complete -c sq-key-subkey-revoke -l notation -d 'Add a notation to the certification'
complete -c sq-key-subkey-revoke -s o -l output -d 'Write to the specified FILE'
complete -c sq-key-subkey-revoke -l revoker -d 'The certificate that issues the revocation'
complete -c sq-key-subkey-revoke -l revoker-file -d 'The certificate that issues the revocation'

