# sq-key-userid-revoke
# Autogenerated from man page /usr/share/man/man1/sq-key-userid-revoke.1.gz
complete -c sq-key-userid-revoke -s B -l binary -d 'Emit binary data'
complete -c sq-key-userid-revoke -l cert -d 'Revoke the user ID on the specified certificate'
complete -c sq-key-userid-revoke -l cert-file -d 'Revoke the user ID on the specified certificate'
complete -c sq-key-userid-revoke -l notation -d 'Add a notation to the certification'
complete -c sq-key-userid-revoke -s o -l output -d 'Write to the specified FILE'
complete -c sq-key-userid-revoke -l revoker -d 'The certificate that issues the revocation'
complete -c sq-key-userid-revoke -l revoker-file -d 'The certificate that issues the revocation'
complete -c sq-key-userid-revoke -l userid -d 'The user ID to revoke'

