# sq-key
# Autogenerated from man page /usr/share/man/man1/sq-key.1.gz
complete -c sq-key -l key -d 'sq key delete Import Alice\'s key.  sq key import alice-secret'
complete -c sq-key -l clear-password -l cert -d 'EB28F26E2739A4870ECC47726F0073F60FD0CBF0 sq key expire Make Alice\'s key expir…'

