# sq-key-password
# Autogenerated from man page /usr/share/man/man1/sq-key-password.1.gz
complete -c sq-key-password -s B -l binary -d 'Emit binary data'
complete -c sq-key-password -l cert -d 'Change the password of the specified certificate\'s keys'
complete -c sq-key-password -l cert-file -d 'Change the password of the specified certificate\'s keys'
complete -c sq-key-password -l clear-password -d 'Clear the password protecting the secret key material'
complete -c sq-key-password -l new-password-file -d 'File containing password to encrypt the secret key material'
complete -c sq-key-password -s o -l output -d 'Write to FILE or stdout if omitted Global options See sq(1) for a description…'

