# sq-key-userid
# Autogenerated from man page /usr/share/man/man1/sq-key-userid.1.gz
complete -c sq-key-userid -l output -d 'Then, strip a User ID: sq key userid strip --userid \'<juliet@example. org>\' \\'

