# sq-key-delete
# Autogenerated from man page /usr/share/man/man1/sq-key-delete.1.gz
complete -c sq-key-delete -s B -l binary -d 'Emit binary data'
complete -c sq-key-delete -l cert -d 'Delete the secret key material from the specified certificate'
complete -c sq-key-delete -l cert-file -d 'Delete the secret key material from the specified certificate'
complete -c sq-key-delete -s o -l output -d 'Write the stripped certificate to the specified file Global options See sq(1)…'

