# sq-network-dane-generate
# Autogenerated from man page /usr/share/man/man1/sq-network-dane-generate.1.gz
complete -c sq-network-dane-generate -l generic -d 'Emit generic resource records [default: OPENPGPKEY records]'
complete -c sq-network-dane-generate -s s -l skip -d 'Skip expired certificates and those that do not have User IDs for given domain'
complete -c sq-network-dane-generate -l size-limit -d 'Try to shrink the certificates to this size'
complete -c sq-network-dane-generate -l ttl -d 'Set the TTL (maximum cache duration) of the resource records'

