# sq-network-wkd-fetch
# Autogenerated from man page /usr/share/man/man1/sq-network-wkd-fetch.1.gz
complete -c sq-network-wkd-fetch -s B -l binary -d 'Emit binary data'
complete -c sq-network-wkd-fetch -l all -d 'Fetch updates for all known certificates'
complete -c sq-network-wkd-fetch -s o -l output -d 'Write to FILE (or stdout when omitted) instead of importing into the certific…'

