# sq-network-keyserver-publish
# Autogenerated from man page /usr/share/man/man1/sq-network-keyserver-publish.1.gz
complete -c sq-network-keyserver-publish -l require-all -d 'Require that all publish operations succeed and return an error otherwise'
complete -c sq-network-keyserver-publish -s s -l server -d 'Set the key server to use.   Can be given multiple times'

