# sq-network-wkd-generate
# Autogenerated from man page /usr/share/man/man1/sq-network-wkd-generate.1.gz
complete -c sq-network-wkd-generate -s d -l direct-method -d 'Use the direct method [default: advanced method]'
complete -c sq-network-wkd-generate -s s -l skip -d 'Skip certificates that do not have User IDs for given domain'

