# sq-pki-list
# Autogenerated from man page /usr/share/man/man1/sq-pki-list.1.gz
complete -c sq-pki-list -s a -l amount -d 'The required amount of trust'
complete -c sq-pki-list -l certification-network -d 'Treats the network as a certification network'
complete -c sq-pki-list -l email -d 'Changes the USERID parameter to match User IDs with the specified email addre…'
complete -c sq-pki-list -l gossip -d 'Treats all certificates as unreliable trust roots'
complete -c sq-pki-list -l show-paths -d 'Show why a binding is authenticated'

