# sq-pki-identify
# Autogenerated from man page /usr/share/man/man1/sq-pki-identify.1.gz
complete -c sq-pki-identify -s a -l amount -d 'The required amount of trust'
complete -c sq-pki-identify -l certification-network -d 'Treats the network as a certification network'
complete -c sq-pki-identify -l gossip -d 'Treats all certificates as unreliable trust roots'
complete -c sq-pki-identify -l show-paths -d 'Show why a binding is authenticated'

