# sq-pki-link-add
# Autogenerated from man page /usr/share/man/man1/sq-pki-link-add.1.gz
complete -c sq-pki-link-add -s a -l amount -d 'Set the amount of trust.   Values between 1 and 120 are meaningful'
complete -c sq-pki-link-add -l all -d 'Link all valid self-signed User ID to the certificate'
complete -c sq-pki-link-add -l ca -d 'Mark the certificate as a certification authority for a  domain'
complete -c sq-pki-link-add -s d -l depth -d 'Set the trust depth (sometimes referred to as the trust level)'
complete -c sq-pki-link-add -l email -d 'An email address to link to the certificate'
complete -c sq-pki-link-add -l expiration -d 'Define EXPIRATION for the acceptance as ISO 8601 formatted string or custom d…'
complete -c sq-pki-link-add -l notation -d 'Add a notation to the certification'
complete -c sq-pki-link-add -l petname -d 'A User ID to link to the certificate'
complete -c sq-pki-link-add -s r -l regex -d 'Add a regular expression to constrain what a trusted introducer can certify'
complete -c sq-pki-link-add -l temporary -d 'Temporarily accepts the binding'
complete -c sq-pki-link-add -l userid -d 'A User ID to link to the certificate.   This must match a self-signed User ID'

