# sq-pki-path
# Autogenerated from man page /usr/share/man/man1/sq-pki-path.1.gz
complete -c sq-pki-path -s a -l amount -d 'The required amount of trust'
complete -c sq-pki-path -l certification-network -d 'Treats the network as a certification network'
complete -c sq-pki-path -l gossip -d 'Treats all certificates as unreliable trust roots'

