# sq-pki-link-retract
# Autogenerated from man page /usr/share/man/man1/sq-pki-link-retract.1.gz
complete -c sq-pki-link-retract -l email -d 'An email address to unlink from the certificate'
complete -c sq-pki-link-retract -l notation -d 'Add a notation to the certification'
complete -c sq-pki-link-retract -l userid -d 'A User ID to unlink from the certificate'

