# sq-pki-authenticate
# Autogenerated from man page /usr/share/man/man1/sq-pki-authenticate.1.gz
complete -c sq-pki-authenticate -s a -l amount -d 'The required amount of trust'
complete -c sq-pki-authenticate -l certification-network -d 'Treats the network as a certification network'
complete -c sq-pki-authenticate -l email -d 'Changes the USERID parameter to match User IDs with the specified email addre…'
complete -c sq-pki-authenticate -l gossip -d 'Treats all certificates as unreliable trust roots'
complete -c sq-pki-authenticate -l show-paths -d 'Show why a binding is authenticated'

