# sq-pki-certify
# Autogenerated from man page /usr/share/man/man1/sq-pki-certify.1.gz
complete -c sq-pki-certify -s B -l binary -d 'Emit binary data'
complete -c sq-pki-certify -s a -l amount -d 'Set the amount of trust.   Values between 1 and 120 are meaningful'
complete -c sq-pki-certify -l add-userid -d 'Add the given user ID if it doesn\'t exist in the certificate'
complete -c sq-pki-certify -l allow-not-alive-certifier -d 'Allow the key to make a certification even if the current time is prior to it…'
complete -c sq-pki-certify -l allow-revoked-certifier -d 'Don\'t fail if the certificate making the certification is revoked'
complete -c sq-pki-certify -l certifier -d 'Create the certification using CERTIFIER-KEY'
complete -c sq-pki-certify -l certifier-file -d 'Create the certification using CERTIFIER-KEY'
complete -c sq-pki-certify -s d -l depth -d 'Set the trust depth (sometimes referred to as the trust level)'
complete -c sq-pki-certify -l email -d 'Treat the given user ID as an email address'
complete -c sq-pki-certify -l expiration -d 'Define EXPIRATION for the certification as ISO 8601 formatted string or custo…'
complete -c sq-pki-certify -s l -l local -d 'Make the certification a local certification'
complete -c sq-pki-certify -l non-revocable -d 'Mark the certification as being non-revocable'
complete -c sq-pki-certify -l notation -d 'Add a notation to the certification'
complete -c sq-pki-certify -s o -l output -d 'Write to FILE or stdout if omitted'
complete -c sq-pki-certify -s r -l regex -d 'Add a regular expression to constrain what a trusted introducer can certify'

