# sq-sign
# Autogenerated from man page /usr/share/man/man1/sq-sign.1.gz
complete -c sq-sign -s B -l binary -d 'Emit binary data'
complete -c sq-sign -s a -l append -d 'Append a signature to existing signature'
complete -c sq-sign -l cleartext-signature -d 'Create a cleartext signature'
complete -c sq-sign -l detached -d 'Create a detached signature'
complete -c sq-sign -l merge -d 'Merge signatures from the input and SIGNED-MESSAGE'
complete -c sq-sign -s n -l notarize -d 'Sign a message and all existing signatures'
complete -c sq-sign -l notation -d 'Add a notation to the certification'
complete -c sq-sign -s o -l output -d 'Write to FILE or stdout if omitted'
complete -c sq-sign -l signer-file -d 'Sign the message using the key in KEY_FILE'
complete -c sq-sign -l signer-key -d 'Sign the message using the specified key on the key store'

