# sq-toolbox-keyring-filter
# Autogenerated from man page /usr/share/man/man1/sq-toolbox-keyring-filter.1.gz
complete -c sq-toolbox-keyring-filter -s B -l binary -d 'Emit binary data'
complete -c sq-toolbox-keyring-filter -s P -l prune-certs -d 'Remove certificate components not matching the filter'
complete -c sq-toolbox-keyring-filter -l domain -d 'Parse user ids into name and email address and case-sensitively matches on th…'
complete -c sq-toolbox-keyring-filter -l email -d 'Parse user ids into name and email address and case-sensitively matches on th…'
complete -c sq-toolbox-keyring-filter -l handle -d 'Match on both primary keys and subkeys, including those certificates that mat…'
complete -c sq-toolbox-keyring-filter -l name -d 'Parse user ids into name and email and case-sensitively matches on the name, …'
complete -c sq-toolbox-keyring-filter -s o -l output -d 'Write to FILE or stdout if omitted'
complete -c sq-toolbox-keyring-filter -l to-cert -d 'Convert any keys in the input to certificates'
complete -c sq-toolbox-keyring-filter -l userid -d 'Case-sensitively matches on the user id, requiring an exact match'

