# sq-toolbox-packet-decrypt
# Autogenerated from man page /usr/share/man/man1/sq-toolbox-packet-decrypt.1.gz
complete -c sq-toolbox-packet-decrypt -s B -l binary -d 'Emit binary data'
complete -c sq-toolbox-packet-decrypt -l dump-session-key -d 'Print the session key to stderr'
complete -c sq-toolbox-packet-decrypt -s o -l output -d 'Write to FILE or stdout if omitted'
complete -c sq-toolbox-packet-decrypt -l recipient-file -d 'Decrypt the message using the key in KEY_FILE'
complete -c sq-toolbox-packet-decrypt -l session-key -d 'Decrypt an encrypted message using SESSION-KEY'

