# sq-toolbox-armor
# Autogenerated from man page /usr/share/man/man1/sq-toolbox-armor.1.gz
complete -c sq-toolbox-armor -l label -d 'Select the kind of armor header'
complete -c sq-toolbox-armor -s o -l output -d 'Write to FILE or stdout if omitted'

