# sq-toolbox-keyring-merge
# Autogenerated from man page /usr/share/man/man1/sq-toolbox-keyring-merge.1.gz
complete -c sq-toolbox-keyring-merge -s B -l binary -d 'Emit binary data'
complete -c sq-toolbox-keyring-merge -s o -l output -d 'Write to FILE or stdout if omitted'

