# sq-toolbox-keyring-list
# Autogenerated from man page /usr/share/man/man1/sq-toolbox-keyring-list.1.gz
complete -c sq-toolbox-keyring-list -l all-userids -d 'List all user ids, even those that are expired, revoked, or not valid under t…'

