# sq-toolbox-packet-join
# Autogenerated from man page /usr/share/man/man1/sq-toolbox-packet-join.1.gz
complete -c sq-toolbox-packet-join -s B -l binary -d 'Emit binary data'
complete -c sq-toolbox-packet-join -l label -d 'Select the kind of armor header'
complete -c sq-toolbox-packet-join -s o -l output -d 'Write to FILE or stdout if omitted'

