# sq-toolbox-extract-cert
# Autogenerated from man page /usr/share/man/man1/sq-toolbox-extract-cert.1.gz
complete -c sq-toolbox-extract-cert -s B -l binary -d 'Emit binary data'
complete -c sq-toolbox-extract-cert -s o -l output -d 'Write to FILE or stdout if omitted'

