# sq-toolbox-packet-dump
# Autogenerated from man page /usr/share/man/man1/sq-toolbox-packet-dump.1.gz
complete -c sq-toolbox-packet-dump -l mpis -d 'Print cryptographic artifacts'
complete -c sq-toolbox-packet-dump -s o -l output -d 'Write to FILE or stdout if omitted'
complete -c sq-toolbox-packet-dump -l recipient-file -d 'Decrypt the message using the key in KEY_FILE'
complete -c sq-toolbox-packet-dump -l session-key -d 'Decrypt an encrypted message using SESSION-KEY'
complete -c sq-toolbox-packet-dump -s x -l hex -d 'Print a hexdump'

