# sq-toolbox-keyring-split
# Autogenerated from man page /usr/share/man/man1/sq-toolbox-keyring-split.1.gz
complete -c sq-toolbox-keyring-split -s B -l binary -d 'Emit binary data'
complete -c sq-toolbox-keyring-split -s p -l prefix -d 'Write to files with PREFIX [defaults: `FILE-` if FILE is set, or `output-` if…'

