# sq-verify
# Autogenerated from man page /usr/share/man/man1/sq-verify.1.gz
complete -c sq-verify -l detached -d 'Verify a detached signature'
complete -c sq-verify -s n -l signatures -d 'Set the threshold of valid signatures to N'
complete -c sq-verify -s o -l output -d 'Write to FILE or stdout if omitted'
complete -c sq-verify -l signer-cert -d 'Verify signatures using the specified certificate'
complete -c sq-verify -l signer-file -d 'Verify signatures using the certificate in CERT_FILE'

