# sq-version
# Autogenerated from man page /usr/share/man/man1/sq-version.1.gz
complete -c sq-version -l default-output-version -d 'List the default output version'
complete -c sq-version -l output-versions -d 'List all the supported output versions Global options See sq(1) for a descrip…'

