# sq
# Autogenerated from man page /usr/share/man/man1/sq.1.gz
complete -c sq -l cert-store -d 'Specify the location of the certificate store'
complete -c sq -s f -l force -d 'Overwrite existing files'
complete -c sq -s h -l help -d 'Print help (see a summary with \'-h\')'
complete -c sq -l home -d 'Set the home directory'
complete -c sq -l key-store -d 'A key store server manages and protects secret key material'
complete -c sq -l keyring -d 'Specify the location of a keyring to use'
complete -c sq -l known-notation -d 'Add NOTATION to the list of known notations'
complete -c sq -l no-cert-store -d 'Disable the use of a certificate store'
complete -c sq -l no-key-store -d 'Disable the use of the key store'
complete -c sq -l output-format -d 'Produce output in FORMAT, if possible'
complete -c sq -l output-version -d 'Produce output variant VERSION, such as 0. 0. 0'
complete -c sq -l password-file -d 'Seed the password cache with the specified password'
complete -c sq -l pep-cert-store -d 'Specify the location of a pEp certificate store'
complete -c sq -l time -d 'Set the reference time as an ISO 8601 formatted timestamp'
complete -c sq -l trust-root -d 'Consider the specified certificate to be a trust root'
complete -c sq -s v -l verbose -d 'Be more verbose.  SUBCOMMANDS sq encrypt Encrypt a message'

